{
 "title": "Loki Kubernetes Event Logs",
 "description": "kubernetes-event-exporter collector Event Logs from Kubernetes, stored in Loki. ",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds", "label": "ds", "query": "loki" },
   { "name": "query", "label": "Search Query word" },
   {
    "name": "namespace",
    "query": {}
   },
   {
    "name": "kind",
    "label": "kind",
    "query": {}
   },
   {
    "name": "name",
    "label": "Name",
    "query": {}
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Events日志分布视图",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "ds",
   "collapsed": true,
   "panels": [
    {
     "title": "Total events by time / $__interval",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(count_over_time({source=\"event-exporter\", namespace=~\"$namespace\", kind!=\"\", kind=~\"$kind\", name!=\"\", name=~\"$name\", severity=~\".*\"} |~ \"(?i)$query\" [$__interval]))",
       "legendFormat": "Log count"
      }
     ]
    },
    {
     "title": "Total event by severity / $__interval",
     "type": "timeseries",
     "description": "severity percentile",
     "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by(severity) (count_over_time({source=\"event-exporter\", namespace=~\"$namespace\", kind!=\"\", kind=~\"$kind\", name!=\"\", name=~\"$name\", severity=~\".*\"} |~ \"(?i)$query\" [$__interval]))"
      }
     ]
    },
    {
     "title": "total event by kind/name / $__interval",
     "type": "timeseries",
     "description": "根据kind/name分组统计Event日志量大小",
     "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(count_over_time({source=\"event-exporter\", namespace=~\"$namespace\", kind!=\"\", kind=~\"$kind\", name!=\"\", name=~\"$name\", severity=~\".*\"} |~ \"(?i)$query\" [$__interval])) by (kind, name)"
      }
     ]
    }
   ]
  },
  { "title": "Event日志面板", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "📃Events Content",
   "type": "logs",
   "description": "Logs from services running in Kubernetes",
   "gridPos": { "h": 28, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "{source=\"event-exporter\", namespace=~\"$namespace\", kind!=\"\", kind=~\"$kind\", name!=\"\", name=~\"$name\", severity=~\".*\"} |~ \"(?i)$query\""
    }
   ]
  }
 ]
}